screenshot_interval_minutes = 10
countdown_interval_seconds = 1

[[taps]]
id = "claim_5d_t"
x = 120
y = 1250
interval_seconds = 60
enabled = true

[[taps]]
id = "restart_tap"
x = 110
y = 1600
interval_seconds = 120
enabled = true

[[taps]]
id = "claim_1d_tap"
x = 350
y = 628
interval_seconds = 15
enabled = true
